#' Simulated multi-channel media spend dataset
#'
#' A simulated dataset containing weekly media spend and conversions for five
#' advertising channels over two years (104 weeks). The data are generated from
#' known response curves (Gompertz, Logistic, and Log-Logistic) with additive
#' Gaussian noise, and are intended for use in package examples and vignettes.
#'
#' @format A tibble with 520 rows and 4 columns:
#' \describe{
#'   \item{channel}{Factor. Advertising channel name. One of
#'     \code{"Paid Search"}, \code{"Paid Social"}, \code{"Display"},
#'     \code{"Online Video"}, \code{"TV"}.}
#'   \item{week}{Date. Week start date (Monday), ranging from
#'     2023-01-02 to 2024-12-23.}
#'   \item{spend}{Integer. Weekly media spend in US dollars.}
#'   \item{conversions}{Integer. Weekly conversions (KPI).}
#' }
#'
#' @details
#' Each channel has a distinct spend scale and response curve shape:
#' \itemize{
#'   \item \strong{Paid Search}: Gompertz curve, ~$45k/week average spend.
#'   \item \strong{Paid Social}: Logistic curve, ~$27k/week average spend.
#'   \item \strong{Display}: Gompertz curve, ~$18k/week average spend.
#'   \item \strong{Online Video}: Logistic curve, ~$34k/week average spend.
#'   \item \strong{TV}: Log-Logistic curve, ~$80k/week average spend.
#' }
#'
#' The dataset is generated by \code{data-raw/mrmopt_data.R}.
#'
#' @examples
#' data(mrmopt_data)
#' mrmopt_data
#'
#' # Filter to a single channel
#' paid_search <- mrmopt_data[mrmopt_data$channel == "Paid Search", ]
"mrmopt_data"

#' Simulated hierarchical TV sub-channel dataset
#'
#' A simulated dataset containing weekly media spend and conversions for eight
#' TV advertising partners nested within three subtypes (Broadcast, Cable,
#' Streaming) over two years (104 weeks). The data are generated from Gompertz
#' response curves with shared structure and unit-level variation, and are
#' intended for demonstrating hierarchical response curve modeling with
#' \code{\link{fit_response_hier}}.
#'
#' @format A tibble with 832 rows and 5 columns:
#' \describe{
#'   \item{subtype}{Factor. TV subtype: \code{"Broadcast"}, \code{"Cable"}, or
#'     \code{"Streaming"}.}
#'   \item{partner}{Factor. Partner name within the subtype (e.g.,
#'     \code{"Network A"}, \code{"Cable One"}, \code{"Stream Alpha"}).}
#'   \item{week}{Date. Week start date (Monday), ranging from
#'     2023-01-02 to 2024-12-23.}
#'   \item{spend}{Integer. Weekly media spend in US dollars.}
#'   \item{conversions}{Integer. Weekly conversions (KPI).}
#' }
#'
#' @details
#' The hierarchy has two levels:
#' \itemize{
#'   \item \strong{Broadcast} (3 partners): Network A (~$35k/week),
#'     Network B (~$28k/week), Network C (~$22k/week)
#'   \item \strong{Cable} (2 partners): Cable One (~$15k/week),
#'     Cable Two (~$12k/week)
#'   \item \strong{Streaming} (3 partners): Stream Alpha (~$10k/week),
#'     Stream Beta (~$8k/week), Stream Gamma (~$6k/week)
#' }
#'
#' All partners share a Gompertz curve family with a common floor (\code{c = 40}).
#' Steepness (\code{b}), ceiling (\code{d}), and midpoint (\code{e}) vary by
#' partner, with partners within the same subtype having more similar parameters.
#'
#' The dataset is generated by \code{data-raw/mrmopt_hier_data.R}.
#'
#' @examples
#' data(mrmopt_hier_data)
#' mrmopt_hier_data
#'
#' # Count partners per subtype
#' table(mrmopt_hier_data$subtype, mrmopt_hier_data$partner)
"mrmopt_hier_data"
